<?php require('apps/delete_article.php'); ?>
<?php require('apps/article_edit_btn.php'); ?>

<h2 class="titre-article"><strong><?=$article['title']?></strong> <small>par <span class="login"><a href="?page=profil&id=<?=$author['id']?>"><?=$author['login']?></a></span></small></h2>
<div class="sous-titres">
	<h4 class="titre-cat"><strong>Catégorie</strong> : <?=$category['name']?></h4>
	<h4 class='titre-note'><?php require('apps/note_display.php'); ?></h4>
</div>

<div class="row">
	<div class="col-md-4">
		<figure><img src='<?=$article['image']?>' alt='Figure' width='100%' /></figure>
	</div>
	<div class="col-md-8">
		<p><?=$article['content']?></p>
		<?php require('apps/note.php') ?>
		<div class="article-back col-md-7 col-sm-7 col-xs-7">
			<a href='?page=artlist'>> Retour aux articles</a>
		</div>
		
	</div>
</div>
<div class="article-com">
	<h3><strong class='com'>Commentaires</strong> :</h3>
	<div class="champ-com">
		<?php require('apps/comments.php') ?>
	</div>
	<?php require('apps/addComment.php'); ?>
	
</div>
