<div class="home col-md-6 col-sm-6 col-xs-12">
	
			
		
	<div class="post"><a href='?page=article&id=<?=$lastArticle['id']?>'>
		<figure class="home-img"><img src='<?=$lastArticle['image']?>' alt='Figure' width='100%' />
			<div class="overlay">
				<div class="overlay-title"><h3><?=$lastArticle['title']?></h3></div>
			</div>
		</figure>
	</a></div>
		<p class="home-category"><i class="fa fa-bookmark"></i> Catégorie : <?=$category['name']?></p>
		<h3><a href='?page=article&id=<?=$lastArticle['id']?>'><?=$lastArticle['title']?></a></h3>
	<div class="separateur"></div>	
	<em><p class="home-date"><i class="fa fa-calendar"></i> <?=$lastArticle['date_post']?> - Par <a href='?page=profil&id=<?=$author['id']?>'><?=$author['login']?></a></p></em>

	<div class"home-content">
		<p><em><?=substr($lastArticle['content'], 0, 120)?>...</em> - <a href='?page=article&id=<?=$lastArticle['id']?>'>Read more</a></p>


</div>
</div>