<form method='post' action='?page=newarticle'>
	<fieldset>
		<legend>Ajouter un article :</legend>
		<div class="col-md-8 col-sm-8 col-xs-12 new-article">
		<form>
			<label for='title'>Titre de l'article :</label>
			<div class="form-group">
				<input class="form-control" type='text' name='title' id='title' placeholder='6-127 car.' value="<?=htmlentities($title)?>" />
			</div>
			<label for='content'>Contenu :</label>
			<div class="form-group">
				<textarea class="form-control" type='textarea' name='content' id='content' placeholder='140-8191 car.' value="<?=htmlentities($content)?>" ></textarea>
			</div>
			<label for='category'>Catégorie :</label>
			<div class="form-group">
				<select class="form-control" name='category' id='category'>
					<option value="<?=htmlentities(1)?>">Tiramisu</option>
					<option value="<?=htmlentities(2)?>">Pizza</option>
					<option value="<?=htmlentities(3)?>">Lapins mutants zombies</option>
					<option value="<?=htmlentities(4)?>">Chèvre miel</option>
				</select>
			</div>
			<label for='image'>Image (optionnel) :</label>
			<div class="form-group">
				<input class="form-control" type='text' name='image' id='image' placeholder="Url de l'image" value='<?=htmlentities($image)?>' />
			</div>
		</form>
		<button class="btn btn-info btn-block" type='submit'>Valider</button>
		</div>
		
	</fieldset>
</form> 