

<h3>Contact</h3>

<div class="list_user">

		<div class="top">
			<ul>
				<li class="pseudos">Pseudos</li>
				<li class="nb_article">Nb articles postés</li>
				<li>Messages privés</li>

			</ul>
		</div>
		  <!-- <tr>
		     <th class="pse">Pseudos</th>
		     <th>Nb articles postés</th>
		     <th>Messages privés</th>
		  </tr>
		 </thead> -->
	<table >
		<tr>
		
		<?php require('apps/user_list.php'); ?>
			
		</tr>
	</table>
	
	

</div>
